### ISSUE TITLE
Homebrew formula for version 1.0.0

### ISSUE THREAD

**Issue by nickbruun** [nickbruun/hayai#28]

**Comment by scribblemaniac** [comment]
I already made a homebrew script for this library a while back for personal use. At the time I did not submit it because I thought it would be rejected (see [Acceptable Formula](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#user-content-niche-or-self-submitted-stuff)). I would probably need to do a bit more testing and formatting before it would be ready but if it's something that interests you I could try and get it together for submission.

**Comment by scribblemaniac** [comment]
I went ahead and worked on this. I ended up having to start the formula from scratch, but it is done now. With almost no troubles, they have accepted my pull request. So now after running `brew update` you can now run `brew cask install hayai` to easily install this library.

The relevant pull request can be found at https://github.com/Homebrew/homebrew/pull/41721.

**Comment by nickbruun** [comment]
@scribblemaniac this is awesome! Thank you so much! :D I'll keep the issue open for post-1.0.0 updates :)
